# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Deploy fixes to other versions with rebase main

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string

permissions: write-all

jobs:
  call-workflow-passing-data:
    uses: Odoo-Ninjas/git-workflows/.github/workflows/deploy_to_subversions.yml@main
    with:
      branches: "11.0 13.0 14.0 15.0 16.0"
    secrets: inherit