# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Deploy fixes to other versions with rebase main

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: setup merge
      run: |
        set -x
        git config --global user.email 'github-action@github.com'
        git config --global user.name 'github-action@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git fetch

    - name: rebase specified branch to specified versions; if fails make issue
      run: |
        SRCBRANCH="${{ inputs.source_branch }}"
        set -x

        for branch in ${{ inputs.branches }}; do
          echo "$branch" > /tmp/input1
          python3 <<END
        import os
        with open("/tmp/input1", "r") as f:
          branch = f.read().strip()
        dest, source = branch.split(":")
        with open("/tmp/vars1", "w") as f:
          f.write(f"export DEST='{dest}'")
        with open("/tmp/vars2", "w") as f:
          f.write(f"export SOURCE='{source}'")
        END
          source /tmp/vars1
          source /tmp/vars2

          git checkout "$SRCBRANCH"
          git log -n1
          git pull

          git checkout "$DEST" -f
          git pull
          git log -n1
          if $(git rebase "$SOURCE"); then
            git push -f
          else
            git rebase --abort || true

            cat .github/workflows/rebase.txt | gh issue create \
              --title "$SOURCE branch was updated - needs to deploy the changes to: $DEST " \
              -F -
          fi
        done
      env:
        GH_TOKEN: ${{ github.token }}