# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Gimera apply and update

on:
  workflow_call:
    inputs:
      params:
        required: false
        type: string

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Run image
      uses: CfirTsabari/actions-pipx@v1.0.2

    - name: add ssh key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        chmod 700 ~/.ssh

    - name: setup git
      run: |
        set -x
        git config --global user.email 'github-action@github.com'
        git config --global user.name 'github-action@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

    - name: rebase main on all versions; if fails make issue
      run: |
        pipx run gimera apply -I ${{ inputs.params }}
      env:
        GH_TOKEN: ${{ github.token }}

    - name: push if changed
      run: |
        git push