# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Run Gimera Update

on:
  workflow_call:
    inputs:
      main_repo:
        required: true
        type: string

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        python-version: "3.10"
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Run image
      uses: CfirTsabari/actions-pipx@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: setup merge
      run: |
        set -x
        git config --global user.email 'github-action@github.com'
        git config --global user.name 'github-action@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git fetch

    - name: rebase main on all versions; if fails make issue
      run: |
        set -x
        env
        git clone ${{ inputs.main_repo }} main_repo
        cd main_repo
        git checkout 11.0 # TODO
        pipx install gimera

      env:
        GH_TOKEN: ${{ github.token }}